Fixes api change introduced in latest wiremock beta. (#246)
* NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.get(Lcom/github/tomakehurst/wiremock/client/UrlMatchingStrategy;)Lcom/github/tomakehurst/wiremock/client/MappingBuilder;